---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: echo
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: oci
  source:
    chart: ealenn/echo-server
    repoURL: https://ealenn.github.io/charts
    targetRevision: 0.5.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - FailOnSharedResource=true